// generateAirports.ts
// Run with: npx tsx generateAirports.ts
// Output: src/data/airports.ts

import Papa from 'papaparse';
import fs from 'fs';
import path from 'path';

const CSV_URL = 'https://ourairports.com/data/airports.csv';
const OUTPUT_PATH = path.join(process.cwd(), 'src/data/airports.ts');

interface RawAirport {
  type: string;
  name: string;
  latitude_deg: string;
  longitude_deg: string;
  iata_code: string;
  municipality: string;
  iso_country: string;
}

export interface Airport {
  iata: string;
  name: string;
  municipality: string;
  country: string;
  lat: number;
  lon: number;
}

async function main() {
  console.log('Fetching airports CSV...');
  const res = await fetch(CSV_URL);
  const csv = await res.text();

  console.log('Parsing...');
  const { data } = Papa.parse<RawAirport>(csv, {
    header: true,
    skipEmptyLines: true,
  });

  const airports: Airport[] = data
    .filter(
      (a) =>
        a.type === 'large_airport' &&
        a.iata_code?.trim() !== '' &&
        a.latitude_deg !== '' &&
        a.longitude_deg !== ''
    )
    .map((a) => ({
      iata: a.iata_code.trim(),
      name: a.name.trim(),
      municipality: a.municipality?.trim() ?? '',
      country: a.iso_country?.trim() ?? '',
      lat: parseFloat(a.latitude_deg),
      lon: parseFloat(a.longitude_deg),
    }))
    .sort((a, b) => a.iata.localeCompare(b.iata));

  console.log(`Found ${airports.length} large airports`);

  const output = `// Auto-generated by generateAirports.ts — do not edit manually
// Source: https://ourairports.com/data/airports.csv

export interface Airport {
  iata: string;
  name: string;
  municipality: string;
  country: string;
  lat: number;
  lon: number;
}

export const AIRPORTS: Airport[] = [\n${airports.map((d) => "\t"+JSON.stringify(d)).join(",\n")}];

export const AIRPORTS_BY_IATA = new Map(AIRPORTS.map(a => [a.iata, a]));
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`Written to ${OUTPUT_PATH}`);
}

main().catch(console.error);